class ErrorCode:
    # --- API-level errors (SEC-7 global handler) ---
    INTERNAL_ERROR = "INTERNAL_ERROR"
    VALIDATION_ERROR = "VALIDATION_ERROR"
    NOT_FOUND = "NOT_FOUND"
    UNAUTHORIZED = "UNAUTHORIZED"

    # --- SSRF (SEC-5) ---
    SSRF_BLOCKED = "SSRF_BLOCKED"
    DOMAIN_UNRESOLVABLE = "DOMAIN_UNRESOLVABLE"

    # --- Audit engine integrity (SEC-1, SEC-2, SEC-16) ---
    SCHEMA_UNVERIFIABLE = "SCHEMA_UNVERIFIABLE"
    ROBOTS_UNVERIFIABLE = "ROBOTS_UNVERIFIABLE"
    LLMS_UNVERIFIABLE = "LLMS_UNVERIFIABLE"
    AUTHORITY_NOT_CONFIGURED = "AUTHORITY_NOT_CONFIGURED"
    TARGET_DOMAIN_REQUIRED = "TARGET_DOMAIN_REQUIRED"
    PAGE_FETCH_FAILED = "PAGE_FETCH_FAILED"

    # --- Idempotency (MF-6) ---
    IDEMPOTENCY_IN_PROGRESS = "IDEMPOTENCY_IN_PROGRESS"


class Severity:
    INFO = "info"
    WARNING = "warning"
    ERROR = "error"
