"""
tests/test_schema_matches_live_db.py

CI schema drift guard for AREOS database.
Verifies that a fresh database boot (migrate + build_kb) produces
an exact match against the canonical schema allowlist.
Prevents dead tables, legacy tables, or uncommitted migrations
from drifting unnoticed.
"""

import os
import sqlite3
import tempfile
import pytest
from pathlib import Path

from areos.db.migrate_audit_tables import migrate
from areos.kb import build_kb
from areos.db.connection import close_all_connections

# Canonical operational tables hand-maintained in areos/db/schema.sql
EXPECTED_OPERATIONAL_TABLES = {
    "_txn_context",
    "audit_phase",
    "audit_runs",
    "audit_synthesis",
    "changelog",
    "idempotency_keys",
    "jobs",
    "manual_observations",
    "manual_verdicts",
    "prompt_sets",
    "sources",
    "sqlite_sequence",  # Internal SQLite table created automatically with AUTOINCREMENT
    "synthesis_prompts",
}

# Canonical KB tables generated by areos/kb/build_kb.py
EXPECTED_KB_TABLES = {
    "kb_check_code_map",
    "kb_embeddings",
    "kb_evidence",
    "kb_meta",
    "kb_metrics",
    "kb_sources",
    "knowledge",
}

# Canonical KB views generated by areos/kb/build_kb.py
EXPECTED_KB_VIEWS = {
    "claims",
}

# Complete allowlist of expected schema objects on a fresh boot
EXPECTED_FRESH_SCHEMA = EXPECTED_OPERATIONAL_TABLES | EXPECTED_KB_TABLES | EXPECTED_KB_VIEWS

# Historical archive tables (present only when migrating legacy v1 databases via scripts/archive_claims_legacy.py)
HISTORICAL_ARCHIVE_TABLES = {
    "claims_v1_archive",
}

# Deprecated/dead tables that MUST NOT exist in a fresh schema (eliminated in Task 7)
PROHIBITED_DEAD_OBJECTS = {
    "tool_landscape",
    "policy_constraints",
    "findings",
    "claim_sources",
    "check_code_mappings",
    "claims_display_rank",
    "claims_legacy",
}


@pytest.fixture
def fresh_db():
    fd, path = tempfile.mkstemp(suffix=".db")
    os.close(fd)
    try:
        migrate(path)
        build_kb.build(path)
        yield path
    finally:
        close_all_connections()
        if os.path.exists(path):
            try:
                os.remove(path)
            except OSError:
                pass


def test_fresh_db_schema_matches_exact_allowlist(fresh_db):
    """
    Assert that a freshly booted DB via migrate() + build_kb.build()
    contains exactly the canonical set of operational tables, KB tables,
    and the claims view.
    """
    conn = sqlite3.connect(fresh_db)
    try:
        rows = conn.execute(
            "SELECT name FROM sqlite_master WHERE type IN ('table', 'view') ORDER BY name"
        ).fetchall()
        actual_objects = {r[0] for r in rows}

        # Assert no schema drift
        missing = EXPECTED_FRESH_SCHEMA - actual_objects
        unexpected = actual_objects - EXPECTED_FRESH_SCHEMA

        assert not missing, f"Schema drift! Missing expected database objects: {sorted(missing)}"
        assert not unexpected, f"Schema drift! Found unexpected database objects: {sorted(unexpected)}"
        assert actual_objects == EXPECTED_FRESH_SCHEMA
    finally:
        conn.close()


def test_no_prohibited_dead_tables_in_fresh_db(fresh_db):
    """
    Assert that none of the dropped legacy FK tables, views, or tables
    reappear in a fresh boot.
    """
    conn = sqlite3.connect(fresh_db)
    try:
        rows = conn.execute(
            "SELECT name FROM sqlite_master WHERE type IN ('table', 'view')"
        ).fetchall()
        actual_objects = {r[0] for r in rows}

        resurrected = actual_objects & PROHIBITED_DEAD_OBJECTS
        assert not resurrected, f"Dead tables resurrected in fresh schema: {sorted(resurrected)}"
    finally:
        conn.close()


def test_claims_is_view_not_table(fresh_db):
    """
    Assert that 'claims' is created as a VIEW over knowledge, not a TABLE.
    """
    conn = sqlite3.connect(fresh_db)
    try:
        row = conn.execute(
            "SELECT type FROM sqlite_master WHERE name = 'claims'"
        ).fetchone()
        assert row is not None, "Expected 'claims' object to exist in sqlite_master"
        assert row[0] == "view", f"Expected 'claims' to be a view, but found type='{row[0]}'"
    finally:
        conn.close()
